version: '3.9'

services:
# PostgreSQL service
  postgres:
    image: postgres:15.3
    env_file:
      - .env
    ports:
      - 5431:${POSTGRES_PORT}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -p ${POSTGRES_PORT} -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 3s
      timeout: 3s
      retries: 5

# Accrual service
  accrual:
    build: 
      context: .
      dockerfile: docker/Dockerfile.accrual
    ports:
      - 8080:${ACCRUAL_PORT}

# Gophermart service
  gophermart:
    build: 
      context: .
      dockerfile: docker/Dockerfile.gophermart
    env_file:
      - .env
    ports:
      - 8081:${HTTP_PORT}
    depends_on:
      postgres:
        condition: service_healthy
      accrual:
        condition: service_started
    