# Builder
FROM golang:alpine AS builder
WORKDIR /gophermart
ADD go.mod .
COPY . .
RUN go build -o cmd/gophermart/gophermart cmd/gophermart/main.go

# Gophermart service
FROM alpine
ENV TZ "Europe/Moscow"
ENV DATABASE_MIGRATIONS "/usr/local/bin/gophermart/migrations"
COPY --from=builder gophermart/cmd/gophermart/gophermart /usr/local/bin/gophermart/
COPY sql/migrations ${DATABASE_MIGRATIONS}
CMD ["/usr/local/bin/gophermart/gophermart"]
