# Accrual service
FROM alpine
RUN mkdir /lib64 && ln -s /lib/libc.musl-x86_64.so.1 /lib64/ld-linux-x86-64.so.2
ENV TZ "Europe/Moscow"
WORKDIR /
ARG TARGETOS TARGETARCH
COPY cmd/accrual/accrual_${TARGETOS}_${TARGETARCH} usr/sbin/accrual/accrual
CMD /usr/sbin/accrual/accrual